name: Build & Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: 'master'

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential cmake git libuv1-dev libssl-dev libhwloc-dev
          version: 1.0

      - name: Build XMRig
        run: |
          mkdir build
          cd build
          cmake .. -DWITH_HWLOC=OFF
          make -j$(nproc)
          mv xmrig server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: build/server

      # 🔥 自动发布到 Releases
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/server
          tag_name: v${{ github.run_number }}
          name: Server Build ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
